version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: sideline_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:7-alpine
    container_name: sideline_redis
    restart: always

  web:
    image: 01646083113/sideline-backend:v1.0.0
    container_name: sideline_web
    ports:
      - "8000:8000"
    environment:
      - PG_DB=${PG_DB}
      - PG_USERNAME=${PG_USERNAME}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_HOST=db
      - PG_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - SELLMMO_KEY=${SELLMMO_KEY}
      - DONGVAN_KEY=${DONGVAN_KEY}
      - MUAVIEW_KEY=${MUAVIEW_KEY}
      - SHOPGMAIL_KEY=${SHOPGMAIL_KEY}
      - GMAIL94_KEY=${GMAIL94_KEY}
      - PROXY_US=${PROXY_US}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - db
      - redis
    restart: always

  celery_worker:
    image: 01646083113/sideline-backend:v1.0.0
    container_name: sideline_worker
    command: celery -A sideline worker -l info -P gevent --concurrency 100 --max-tasks-per-child 500
    environment:
      - PG_DB=${PG_DB}
      - PG_USERNAME=${PG_USERNAME}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_HOST=db
      - REDIS_URL=redis://redis:6379/0
      - SELLMMO_KEY=${SELLMMO_KEY}
      - DONGVAN_KEY=${DONGVAN_KEY}
      - MUAVIEW_KEY=${MUAVIEW_KEY}
      - SHOPGMAIL_KEY=${SHOPGMAIL_KEY}
      - GMAIL94_KEY=${GMAIL94_KEY}
      - PROXY_US=${PROXY_US}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - db
      - redis
    restart: always

  celery_beat:
    image: 01646083113/sideline-backend:v1.0.0
    container_name: sideline_beat
    command: celery -A sideline beat -l info
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PROXY_US=${PROXY_US}
    depends_on:
      - redis
    restart: always

volumes:
  postgres_data: