version: '3.8'

services:
  db:
    image: postgres:15
    container_name: sideline_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: always

  web:
    image: 01646083113/sideline-backend:v1.0.0
    container_name: sideline_web
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=True
    depends_on:
      - db
    restart: always

volumes:
  postgres_data: