# Generated by Django 4.2 on 2025-10-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('provider', models.CharField(choices=[('pinger', 'Pinger'), ('textnow', 'TextNow'), ('sideline', 'Sideline'), ('googlevoice', 'Google Voice'), ('other', 'Other')], default='pinger', max_length=30)),
                ('status', models.CharField(choices=[('live', 'Live'), ('lock', 'Locked'), ('die', 'Dead')], default='live', max_length=10)),
                ('batch', models.TextField(blank=True, null=True)),
                ('batch_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('message_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('media', models.TextField(blank=True, null=True)),
                ('media_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'phone_account',
                'ordering': ['phone'],
            },
        ),
    ]
