# Generated by Django 4.2 on 2025-10-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_employee_customer_phoneaccount_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneaccount',
            name='batch_hash',
        ),
        migrations.RemoveField(
            model_name='phoneaccount',
            name='media_hash',
        ),
        migrations.RemoveField(
            model_name='phoneaccount',
            name='message_hash',
        ),
    ]
