# Generated by Django 4.2 on 2025-11-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_phoneaccount_batch_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('dongvan', 'DongVan'), ('sellmmo', 'SellMMO'), ('fbclones', 'FBClones'), ('shopgmail', 'ShopGmail')], max_length=100, unique=True)),
                ('base_url', models.URLField()),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
