# Generated by Django 4.2 on 2025-11-02 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_mailprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên loại mail: HotMail NEW - 50d', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, help_text='Giá bán / 1 mail', max_digits=12)),
                ('note', models.TextField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_types', to='customer.mailprovider')),
            ],
        ),
    ]
