# Generated by Django 4.2 on 2025-11-02 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_mailtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.employee')),
                ('mail_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='customer.mailtype')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='customer.mailprovider')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('auth_code', models.CharField(blank=True, max_length=255, null=True)),
                ('copied', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='customer.mailpurchase')),
            ],
            options={
                'unique_together': {('purchase', 'email')},
            },
        ),
    ]
