# Generated by Django 4.2 on 2025-11-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_mailpurchase_purchasedmail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtype',
            name='provider',
        ),
        migrations.AlterUniqueTogether(
            name='purchasedmail',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='purchasedmail',
            name='purchase',
        ),
        migrations.AlterField(
            model_name='mailpurchase',
            name='mail_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mailpurchase',
            name='provider',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='MailProvider',
        ),
        migrations.DeleteModel(
            name='MailType',
        ),
        migrations.DeleteModel(
            name='PurchasedMail',
        ),
    ]
