# Generated by Django 4.2 on 2025-11-02 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_mailtype_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('base_url', models.URLField()),
                ('api_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='mailpurchase',
            old_name='request_payload',
            new_name='raw_response',
        ),
        migrations.RemoveField(
            model_name='mailpurchase',
            name='mail_type',
        ),
        migrations.RemoveField(
            model_name='mailpurchase',
            name='response_data',
        ),
        migrations.AddField(
            model_name='mailpurchase',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mailpurchase',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mailpurchase',
            name='trans_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mailpurchase',
            name='status',
            field=models.CharField(default='success', max_length=20),
        ),
        migrations.AlterField(
            model_name='mailpurchase',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.mailprovider'),
        ),
        migrations.CreateModel(
            name='PurchasedMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='customer.mailpurchase')),
            ],
            options={
                'unique_together': {('purchase', 'email')},
            },
        ),
    ]
