# Generated by Django 4.2 on 2025-11-02 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_purchasedmail_client_id_purchasedmail_is_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextNowAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_textnow', models.BooleanField(default=True)),
                ('api_key', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textnow_accounts', to='customer.employee')),
            ],
            options={
                'db_table': 'textnow_account',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppleMailProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('proxy_ip', models.GenericIPAddressField(unpack_ipv4=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apple_mail_entries', to='customer.employee')),
            ],
            options={
                'db_table': 'apple_mail_proxy',
                'ordering': ['-created_at'],
            },
        ),
    ]
