# Generated by Django 4.2 on 2025-11-03 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_textnowaccount_applemailproxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textnowaccount',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='textnowaccount',
            name='is_textnow',
        ),
    ]
