# Generated by Django 4.2 on 2025-11-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_remove_textnowaccount_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applemailproxy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='phoneaccount',
            name='provider',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
