# Generated by Django 4.2 on 2025-11-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_applemailproxy_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneaccount',
            name='provider',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
