# Generated by Django 4.2 on 2025-11-04 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_remove_employee_groups_employee_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
    ]
