# Generated by Django 4.2 on 2025-11-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_remove_customer_address_remove_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneaccount',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
