# Generated by Django 4.2 on 2025-11-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_phoneaccount_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_assigned_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
