# Generated by Django 4.2 on 2025-11-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_remove_customer_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeegroup',
            name='description',
        ),
    ]
