# Generated by Django 4.2 on 2025-11-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_remove_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='raw_password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='raw_password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
