# Generated by Django 4.2 on 2025-11-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_customer_raw_password_employee_raw_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeegroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
