# Generated by Django 4.2 on 2025-11-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_alter_employeegroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneaccount',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('live_use', 'Live Use'), ('lock', 'Locked'), ('die', 'Dead')], default='live', max_length=10),
        ),
    ]
