# Generated by Django 4.2 on 2025-11-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_alter_phoneaccount_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneaccount',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('die_use', 'Dead (When In Use)'), ('lock', 'Locked'), ('die', 'Dead')], default='live', max_length=10),
        ),
    ]
