# Generated by Django 4.2 on 2025-11-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_alter_phoneaccount_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailPurchase',
            new_name='MailTransaction',
        ),
    ]
