# Generated by Django 4.2 on 2025-11-12 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_phoneaccount_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='applemailproxy',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_apple_mail', to='app.employee'),
        ),
        migrations.AlterField(
            model_name='applemailproxy',
            name='proxy_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
