# Generated by Django 4.2 on 2025-11-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_applemailproxy_creator_alter_applemailproxy_proxy_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneaccount',
            name='provider',
            field=models.CharField(default='Pinger/Textfree', max_length=30),
        ),
    ]
