# Generated by Django 4.2 on 2025-11-13 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_phoneaccount_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applemailproxy',
            name='creator',
        ),
    ]
