# Generated by Django 4.2 on 2025-11-13 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_applemailproxy_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneaccount',
            name='purchased_mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_by_phones', to='app.purchasedmail'),
        ),
    ]
