# Generated by Django 4.2 on 2025-11-14 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customer_created_at_customer_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_at',
        ),
    ]
