# Generated by Django 4.2 on 2025-11-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customer_created_at_customer_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedmail',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
