# Generated by Django 4.2 on 2025-11-15 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_purchasedmail_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='provided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CustomerAssignHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_count', models.PositiveIntegerField()),
                ('created_list', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_assign_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
