# Generated by Django 4.2 on 2025-11-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_customer_is_provided_customer_provided_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_provided',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='provided_at',
        ),
    ]
