# Generated by Django 4.2 on 2025-11-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_customer_is_provided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_message_first',
            field=models.BooleanField(default=False),
        ),
    ]
