# Generated by Django 4.2 on 2025-11-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_messagehistorylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_use',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
