# Generated by Django 4.2 on 2025-11-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_customer_date_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_message_first',
        ),
    ]
