# Generated by Django 4.2 on 2025-11-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_customer_is_message_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_use',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
