# Generated by Django 4.2 on 2025-11-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_customer_date_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerassignhistory',
            name='reset_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerassignhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
