# Generated by Django 4.2 on 2025-12-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_customerassignhistory_reset_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerassignhistory',
            name='is_revoke',
            field=models.BooleanField(default=False),
        ),
    ]
