# Generated by Django 4.2 on 2026-05-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_customerassignhistory_is_revoke'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_us', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proxy Setting',
                'db_table': 'proxy_setting',
            },
        ),
    ]
