MESSAGE_STATUS = [
    (MESSAGE_STATUS_PENDING, MESSAGE_STATUS_PENDING),
    (MESSAGE_STATUS_SUCCESS, MESSAGE_STATUS_SUCCESS),
    (MESSAGE_STATUS_FAIL, MESSAGE_STATUS_FAIL)
]

MESSAGE_STATUS_PENDING = 'pending'
MESSAGE_STATUS_SUCCESS = 'success'
MESSAGE_STATUS_FAIL = 'fail'
