
"""
Django settings for sideline project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os
from logzero import logger, logfile
import sys
from logging import Formatter
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-97@7qqje=$3f)%t)lkt(#03j25#i#+hh-2+zb*la$w9$6z68i1')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # "app.middleware.disable_csrf_for_api.DisableCSRFForAPI",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    "EXCEPTION_HANDLER": "app.exceptions.custom_exception_handler",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",   # user chưa đăng nhập
        "rest_framework.throttling.UserRateThrottle",   # user đăng nhập
        "rest_framework.throttling.ScopedRateThrottle", # giới hạn theo từng API
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "50/min",        # 60 request/phút cho IP ẩn danh
        "user": "1000/min",       # 600 request/phút cho user đã login
        'ip_global': '1000/min',
        "login": "13/second",          # API login
        "token_refresh": "13/second", # refresh token
        "logout": "13/second",        # logout
        'light': '100/second',       # API nhẹ (GET info, list, v.v.)
        'medium': '100/second',       # API tương tác (chat, gửi tin)
        'heavy': '100/second',        # API nặng (mua mail, upload)
    },
}
ROOT_URLCONF = 'sideline.urls'

# ✅ Chỉ định rõ domain frontend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # frontend dev
    "http://38.145.199.150",
    "https://sideliine.com"
]

CSRF_TRUSTED_ORIGINS = ["http://38.145.199.150", "http://localhost:5173", "https://sideliine.com"]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.ngrok-free\.dev$",
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=200),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3),
}


# --------- cau hinh luu log ----------------------
LOG_DIR = "/var/log/sideline"
LOG_FILE = os.path.join(LOG_DIR, "app.log")

os.makedirs(LOG_DIR, exist_ok=True)

logfile(LOG_FILE, maxBytes=10 * 1024 * 1024, backupCount=5)
logger.debug(f"Log directory: {LOG_FILE}")

# 🧩 Redirect print() và lỗi ra file luôn
sys.stdout = open(LOG_FILE, "a+", buffering=1)  # ghi từng dòng
sys.stderr = open(LOG_FILE, "a+", buffering=1)

# Cấu hình logging chuẩn
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {name}:{lineno} - {message}",
            "style": "{",
        },
    },

    "handlers": {
        "app_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "level": "DEBUG",
            "filename": "/var/log/sideline/app.log",
            "formatter": "verbose",
            "maxBytes": 10 * 1024 * 1024,
            "backupCount": 5,
            "delay": True,
        },

        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },

        "celery_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "level": "INFO",
            "filename": "/var/log/sideline/celery.log",
            "formatter": "verbose",
            "maxBytes": 10 * 1024 * 1024,
            "backupCount": 5,
            "delay": True,
        }
    },

    "root": {
        "handlers": ["app_file", "console"],
        "level": "DEBUG",
    },

    "loggers": {
        "django.request": {
            "handlers": ["app_file", "console"],
            "level": "INFO",
            "propagate": False,
        },

        "celery": {
            "handlers": ["celery_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
# -------------------------------------------------------

# ✅ Cho phép gửi cookie / header Authorization
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True
# ✅ Cho phép một số header cụ thể
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "csrftoken", 
    "x-requested-with",
    "x-timezone",       
    
]

CSRF_COOKIE_NAME = 'sideline_csrftoken'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sideline.wsgi.application'
CORS_ALLOW_CREDENTIALS = True


SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_TASK_TRACK_STARTED = True
CELERY_RESULT_EXTENDED = True
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
    }
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('PG_DB'),
        'USER': os.environ.get('PG_USERNAME'),
        'PASSWORD': os.environ.get('PG_PASSWORD'),
        'HOST': os.environ.get('PG_HOST', 'localhost'),
        'PORT': os.environ.get('PG_PORT', '5432'),
    }
}
SWAGGER_SETTINGS = {
    # 'VALIDATOR_URL': 'http://localhost:8000',
    # "exclude_namespaces": [],  # List URL namespaces to ignore
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder'
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# STATICFILES_DIRS = [
#     BASE_DIR / 'customer' / 'static'
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
